# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/eslacker/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake

# The command to remove a file.
RM = /Users/eslacker/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/eslacker/CLionProjects/SNek

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/eslacker/CLionProjects/SNek

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Users/eslacker/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/eslacker/CLionProjects/SNek/CMakeFiles /Users/eslacker/CLionProjects/SNek//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/eslacker/CLionProjects/SNek/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SNek

# Build rule for target.
SNek: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SNek
.PHONY : SNek

# fast build rule for target.
SNek/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/build
.PHONY : SNek/fast

Buffer.o: Buffer.cpp.o
.PHONY : Buffer.o

# target to build an object file
Buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Buffer.cpp.o
.PHONY : Buffer.cpp.o

Buffer.i: Buffer.cpp.i
.PHONY : Buffer.i

# target to preprocess a source file
Buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Buffer.cpp.i
.PHONY : Buffer.cpp.i

Buffer.s: Buffer.cpp.s
.PHONY : Buffer.s

# target to generate assembly for a file
Buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Buffer.cpp.s
.PHONY : Buffer.cpp.s

DoubleBuffer.o: DoubleBuffer.cpp.o
.PHONY : DoubleBuffer.o

# target to build an object file
DoubleBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/DoubleBuffer.cpp.o
.PHONY : DoubleBuffer.cpp.o

DoubleBuffer.i: DoubleBuffer.cpp.i
.PHONY : DoubleBuffer.i

# target to preprocess a source file
DoubleBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/DoubleBuffer.cpp.i
.PHONY : DoubleBuffer.cpp.i

DoubleBuffer.s: DoubleBuffer.cpp.s
.PHONY : DoubleBuffer.s

# target to generate assembly for a file
DoubleBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/DoubleBuffer.cpp.s
.PHONY : DoubleBuffer.cpp.s

GameWindow.o: GameWindow.cpp.o
.PHONY : GameWindow.o

# target to build an object file
GameWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/GameWindow.cpp.o
.PHONY : GameWindow.cpp.o

GameWindow.i: GameWindow.cpp.i
.PHONY : GameWindow.i

# target to preprocess a source file
GameWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/GameWindow.cpp.i
.PHONY : GameWindow.cpp.i

GameWindow.s: GameWindow.cpp.s
.PHONY : GameWindow.s

# target to generate assembly for a file
GameWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/GameWindow.cpp.s
.PHONY : GameWindow.cpp.s

Levels.o: Levels.cpp.o
.PHONY : Levels.o

# target to build an object file
Levels.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Levels.cpp.o
.PHONY : Levels.cpp.o

Levels.i: Levels.cpp.i
.PHONY : Levels.i

# target to preprocess a source file
Levels.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Levels.cpp.i
.PHONY : Levels.cpp.i

Levels.s: Levels.cpp.s
.PHONY : Levels.s

# target to generate assembly for a file
Levels.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Levels.cpp.s
.PHONY : Levels.cpp.s

Menu/GameOverMenu.o: Menu/GameOverMenu.cpp.o
.PHONY : Menu/GameOverMenu.o

# target to build an object file
Menu/GameOverMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/GameOverMenu.cpp.o
.PHONY : Menu/GameOverMenu.cpp.o

Menu/GameOverMenu.i: Menu/GameOverMenu.cpp.i
.PHONY : Menu/GameOverMenu.i

# target to preprocess a source file
Menu/GameOverMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/GameOverMenu.cpp.i
.PHONY : Menu/GameOverMenu.cpp.i

Menu/GameOverMenu.s: Menu/GameOverMenu.cpp.s
.PHONY : Menu/GameOverMenu.s

# target to generate assembly for a file
Menu/GameOverMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/GameOverMenu.cpp.s
.PHONY : Menu/GameOverMenu.cpp.s

Menu/LeaderboardMenu.o: Menu/LeaderboardMenu.cpp.o
.PHONY : Menu/LeaderboardMenu.o

# target to build an object file
Menu/LeaderboardMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/LeaderboardMenu.cpp.o
.PHONY : Menu/LeaderboardMenu.cpp.o

Menu/LeaderboardMenu.i: Menu/LeaderboardMenu.cpp.i
.PHONY : Menu/LeaderboardMenu.i

# target to preprocess a source file
Menu/LeaderboardMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/LeaderboardMenu.cpp.i
.PHONY : Menu/LeaderboardMenu.cpp.i

Menu/LeaderboardMenu.s: Menu/LeaderboardMenu.cpp.s
.PHONY : Menu/LeaderboardMenu.s

# target to generate assembly for a file
Menu/LeaderboardMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/LeaderboardMenu.cpp.s
.PHONY : Menu/LeaderboardMenu.cpp.s

Menu/MainMenu.o: Menu/MainMenu.cpp.o
.PHONY : Menu/MainMenu.o

# target to build an object file
Menu/MainMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/MainMenu.cpp.o
.PHONY : Menu/MainMenu.cpp.o

Menu/MainMenu.i: Menu/MainMenu.cpp.i
.PHONY : Menu/MainMenu.i

# target to preprocess a source file
Menu/MainMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/MainMenu.cpp.i
.PHONY : Menu/MainMenu.cpp.i

Menu/MainMenu.s: Menu/MainMenu.cpp.s
.PHONY : Menu/MainMenu.s

# target to generate assembly for a file
Menu/MainMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/MainMenu.cpp.s
.PHONY : Menu/MainMenu.cpp.s

Menu/MenuBase.o: Menu/MenuBase.cpp.o
.PHONY : Menu/MenuBase.o

# target to build an object file
Menu/MenuBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/MenuBase.cpp.o
.PHONY : Menu/MenuBase.cpp.o

Menu/MenuBase.i: Menu/MenuBase.cpp.i
.PHONY : Menu/MenuBase.i

# target to preprocess a source file
Menu/MenuBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/MenuBase.cpp.i
.PHONY : Menu/MenuBase.cpp.i

Menu/MenuBase.s: Menu/MenuBase.cpp.s
.PHONY : Menu/MenuBase.s

# target to generate assembly for a file
Menu/MenuBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/MenuBase.cpp.s
.PHONY : Menu/MenuBase.cpp.s

Menu/PauseMenu.o: Menu/PauseMenu.cpp.o
.PHONY : Menu/PauseMenu.o

# target to build an object file
Menu/PauseMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/PauseMenu.cpp.o
.PHONY : Menu/PauseMenu.cpp.o

Menu/PauseMenu.i: Menu/PauseMenu.cpp.i
.PHONY : Menu/PauseMenu.i

# target to preprocess a source file
Menu/PauseMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/PauseMenu.cpp.i
.PHONY : Menu/PauseMenu.cpp.i

Menu/PauseMenu.s: Menu/PauseMenu.cpp.s
.PHONY : Menu/PauseMenu.s

# target to generate assembly for a file
Menu/PauseMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/Menu/PauseMenu.cpp.s
.PHONY : Menu/PauseMenu.cpp.s

SnakeMovement.o: SnakeMovement.cpp.o
.PHONY : SnakeMovement.o

# target to build an object file
SnakeMovement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/SnakeMovement.cpp.o
.PHONY : SnakeMovement.cpp.o

SnakeMovement.i: SnakeMovement.cpp.i
.PHONY : SnakeMovement.i

# target to preprocess a source file
SnakeMovement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/SnakeMovement.cpp.i
.PHONY : SnakeMovement.cpp.i

SnakeMovement.s: SnakeMovement.cpp.s
.PHONY : SnakeMovement.s

# target to generate assembly for a file
SnakeMovement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/SnakeMovement.cpp.s
.PHONY : SnakeMovement.cpp.s

SnakePlayfield.o: SnakePlayfield.cpp.o
.PHONY : SnakePlayfield.o

# target to build an object file
SnakePlayfield.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/SnakePlayfield.cpp.o
.PHONY : SnakePlayfield.cpp.o

SnakePlayfield.i: SnakePlayfield.cpp.i
.PHONY : SnakePlayfield.i

# target to preprocess a source file
SnakePlayfield.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/SnakePlayfield.cpp.i
.PHONY : SnakePlayfield.cpp.i

SnakePlayfield.s: SnakePlayfield.cpp.s
.PHONY : SnakePlayfield.s

# target to generate assembly for a file
SnakePlayfield.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/SnakePlayfield.cpp.s
.PHONY : SnakePlayfield.cpp.s

WindowManager.o: WindowManager.cpp.o
.PHONY : WindowManager.o

# target to build an object file
WindowManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/WindowManager.cpp.o
.PHONY : WindowManager.cpp.o

WindowManager.i: WindowManager.cpp.i
.PHONY : WindowManager.i

# target to preprocess a source file
WindowManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/WindowManager.cpp.i
.PHONY : WindowManager.cpp.i

WindowManager.s: WindowManager.cpp.s
.PHONY : WindowManager.s

# target to generate assembly for a file
WindowManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/WindowManager.cpp.s
.PHONY : WindowManager.cpp.s

controls.o: controls.cpp.o
.PHONY : controls.o

# target to build an object file
controls.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/controls.cpp.o
.PHONY : controls.cpp.o

controls.i: controls.cpp.i
.PHONY : controls.i

# target to preprocess a source file
controls.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/controls.cpp.i
.PHONY : controls.cpp.i

controls.s: controls.cpp.s
.PHONY : controls.s

# target to generate assembly for a file
controls.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/controls.cpp.s
.PHONY : controls.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SNek.dir/build.make CMakeFiles/SNek.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SNek"
	@echo "... Buffer.o"
	@echo "... Buffer.i"
	@echo "... Buffer.s"
	@echo "... DoubleBuffer.o"
	@echo "... DoubleBuffer.i"
	@echo "... DoubleBuffer.s"
	@echo "... GameWindow.o"
	@echo "... GameWindow.i"
	@echo "... GameWindow.s"
	@echo "... Levels.o"
	@echo "... Levels.i"
	@echo "... Levels.s"
	@echo "... Menu/GameOverMenu.o"
	@echo "... Menu/GameOverMenu.i"
	@echo "... Menu/GameOverMenu.s"
	@echo "... Menu/LeaderboardMenu.o"
	@echo "... Menu/LeaderboardMenu.i"
	@echo "... Menu/LeaderboardMenu.s"
	@echo "... Menu/MainMenu.o"
	@echo "... Menu/MainMenu.i"
	@echo "... Menu/MainMenu.s"
	@echo "... Menu/MenuBase.o"
	@echo "... Menu/MenuBase.i"
	@echo "... Menu/MenuBase.s"
	@echo "... Menu/PauseMenu.o"
	@echo "... Menu/PauseMenu.i"
	@echo "... Menu/PauseMenu.s"
	@echo "... SnakeMovement.o"
	@echo "... SnakeMovement.i"
	@echo "... SnakeMovement.s"
	@echo "... SnakePlayfield.o"
	@echo "... SnakePlayfield.i"
	@echo "... SnakePlayfield.s"
	@echo "... WindowManager.o"
	@echo "... WindowManager.i"
	@echo "... WindowManager.s"
	@echo "... controls.o"
	@echo "... controls.i"
	@echo "... controls.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

